---
ID: "ecf91734-cc9d-45c5-b106-e5c8e411130e"
Parent: "7167ab53-837e-4365-9288-8f28616be4db"
Template: "fcd285da-9ab2-4c8d-b185-5a7487a9ba1b"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Presentation/Rendering Variants/Search Results/detail/Text/Summary/Product Descriptoin
DB: master
SharedFields:
- ID: "4753764c-c05a-4623-841b-97f85135241c"
  Hint: FieldName
  Value: Description
- ID: "7495124d-09b5-4cb3-b4a6-fe77a95827da"
  Hint: CssClass
  Value: "field-summary"
- ID: "db805bdc-8eec-4238-b174-2427b6f1f077"
  Hint: Tag
  Value: "{18C8C889-C723-452A-970C-7CE4D41EE371}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180216T203254Z
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T132928Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        CommerceUsers\Anonymous
