---
ID: "c4ed188b-c54d-40b4-b438-6b8a6ef9d2df"
Parent: "a5beea20-dc20-45b4-b894-e0ca5c2e4726"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/Habitat Sites/Habitat Home Store/styles/pages/product-details-page Copied from Storefront Branded Extension"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/061CBF948C034F59B3DECCFC6ECD77CE.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "705951fe-6a71-44be-99ab-e6273d9a398d"
  Value: LypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KQG1lZGlhIChtYXgtd2lkdGg6IDk5MXB4KSB7CiAgLnByb2R1Y3QtZGV0YWlscy1wYWdlIC5wcm9kdWN0LWltYWdlcyB7CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgfQp9CgpAbWVkaWEgKG1heC13aWR0aDogOTkxcHgpIHsKICAucHJvZHVjdC1kZXRhaWxzLXBhZ2UgLnByb2R1Y3QtaW1hZ2VzIHVsIHsKICAgIGRpc3BsYXk6IC13ZWJraXQtaW5saW5lLWJveDsKICAgIGRpc3BsYXk6IC1tcy1pbmxpbmUtZmxleGJveDsKICAgIGRpc3BsYXk6IGlubGluZS1mbGV4OwogICAgbWFyZ2luLWJvdHRvbTogMjVweDsKICB9Cn0KCi5wcm9kdWN0LWRldGFpbHMtcGFnZSAucHJvZHVjdC1saXN0IHsKICBtYXJnaW46IDMwcHggMCA0NXB4IDA7Cn0KCi5wcm9kdWN0LWRldGFpbHMtcGFnZSAucHJvZHVjdC1saXN0ID4gdWwgewogIG1hcmdpbi1sZWZ0OiAtMC44ZW07Cn0KCi5wcm9kdWN0LWRldGFpbHMtcGFnZSA+IC5jb21wb25lbnQuY29sdW1uLXNwbGl0dGVyID4gZGl2Omxhc3QtY2hpbGQgewogIG1hcmdpbi1sZWZ0OiAwOwogIG1hcmdpbi1yaWdodDogMDsKfQoKQG1lZGlhIChtYXgtd2lkdGg6IDk5MXB4KSB7CiAgLnByb2R1Y3QtZGV0YWlscy1wYWdlID4gLmNvbXBvbmVudC5jb2x1bW4tc3BsaXR0ZXIgPiBkaXY6Zmlyc3QtY2hpbGQgewogICAgcGFkZGluZzogMDsKICB9Cn0KCi5wcm9kdWN0LWRldGFpbHMtcGFnZSAuY29udGFpbmVyLXJvdW5kZWQgewogIHBhZGRpbmc6IDQwcHggNDBweCAzMXB4IDQwcHg7CiAgaGVpZ2h0OiAxMDAlOwogIG1pbi1oZWlnaHQ6IDQ0MXB4Owp9CgpAbWVkaWEgKG1heC13aWR0aDogOTkxcHgpIHsKICAucHJvZHVjdC1kZXRhaWxzLXBhZ2UgLmNvbnRhaW5lci1yb3VuZGVkIHsKICAgIHBhZGRpbmc6IDMwcHg7CiAgfQp9CgoucHJvZHVjdC1kZXRhaWxzLXBhZ2UgLmNvbnRhaW5lci1yb3VuZGVkIC5wcm9kdWN0LWluZm8gLnByb2R1Y3QtbmFtZSB7CiAgbWFyZ2luLWJvdHRvbTogMTBweDsKfQoKLnByb2R1Y3QtZGV0YWlscy1wYWdlIC5jb250YWluZXItcm91bmRlZCAucHJvZHVjdC1pbmZvIC5wcm9kdWN0LW5hbWUgaDEgewogIG1hcmdpbi10b3A6IDA7CiAgbGluZS1oZWlnaHQ6IDEyNSU7CiAgZm9udC13ZWlnaHQ6IDUwMDsKICBjb2xvcjogIzM4M2M0MTsKICBmb250LWZhbWlseTogJ0tpZXZpdFBybycgIWltcG9ydGFudDsKfQo=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2582
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: text/css
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: css
Languages:
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180228T063953Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180228T063953Z
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180228T063953Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180228T063953Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
