---
ID: "0b1558bc-938d-43e8-90d7-fe9bd62982f9"
Parent: "13299a4c-9fca-4ec9-b936-90eb48afc316"
Template: "13299a4c-9fca-4ec9-b936-90eb48afc316"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Store/Account Management/My Wishlist/__Standard Values
DB: master
SharedFields:
- ID: "d4952280-2d7d-4bf4-a99a-ea36dad0f0a7"
  Hint: Body Css Class
  Value: "my-order-page"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170811T075357Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
