---
ID: "549841dc-15d9-4c38-9ed4-2935cb027c02"
Parent: "56c193d5-529c-4951-9d69-d7705bea68f7"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: "/sitecore/media library/Project/Habitat Sites/Habitat Home/Images/Productivity - Computers and Tablets/Product Images"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180621T140344Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
