---
ID: "88064982-2f4b-4f08-802c-9438c91412d9"
Parent: "4a53115b-cd24-4559-a500-cd4aa9aebf80"
Template: "6b8aabef-d650-46e0-97d0-c0b04f7f016b"
Path: "/sitecore/content/Habitat Sites/Habitat Home/Presentation/Styles/Custom/Store/product-detail-images"
DB: master
SharedFields:
- ID: "09147fb2-ebfb-4949-8c8e-26a424409d5e"
  Hint: Value
  Value: "product-detail-image-col"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180227T171422Z
