---
ID: "fd3d824e-6d2b-4f3d-b3f3-395162244dcb"
Parent: "f9ecdcca-4936-4c32-b2df-508c9e3285d5"
Template: "7c02e9f5-54b5-4ef4-bd10-f4c5d448a48c"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Presentation/Rendering Variants/Search Results/detail/Text/Product Labels/Product
DB: master
SharedFields:
- ID: "1aa68c0b-eb67-4575-9ca8-1689c2aff091"
  Hint: Tag
  Value: "{E8E2C26D-2F96-4A9C-9C17-D095E6CE46CC}"
- ID: "8414031e-7b85-426c-8516-84d6223a1208"
  Hint: CssClass
  Value: "label label-info"
- ID: "9649a336-0dc1-4133-89ed-6d76beb4c32e"
  Hint: EnableRule
  Type: Rules
  Value: |
    <ruleset>
      <rule
        uid="{5B12266C-1EED-4E3B-B389-C9B9D6170860}">
        <conditions>
          <or
            uid="49D41B4F141D4A228E7CDAD265828B67">
            <condition
              id="{D0810F9D-734C-452D-BBB6-4730368D68F1}"
              uid="2A51F7DE997F4D7A8331CFB5F7F0CC82"
              templateid="{63842356-2202-46C3-AB72-17E79EF4CA2D}" />
            <condition
              id="{D0810F9D-734C-452D-BBB6-4730368D68F1}"
              uid="1AE324E9810241C58534BC680EEAD127"
              templateid="{2526FABE-B1A6-461E-A42A-CBB108DB1190}" />
          </or>
        </conditions>
      </rule>
    </ruleset>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: Product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180502T163559Z
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T132925Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        CommerceUsers\Anonymous
