---
ID: "c1f44e19-5b84-4b2c-9386-8d189476028d"
Parent: "fb28d141-9fe5-457a-ba32-be7241528401"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Habitat Home/Product Related Content/Product Related Content
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/elements4.png
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{03592CD2-4FEC-4ACB-87FC-9A3B1F18894D}"
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductRelatedContent
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Sitecore.HabitatHome.Feature.ProductRelatedContent.Controllers.ProductRelatedContentController, Sitecore.HabitatHome.Feature.ProductRelatedContent
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180531T205531Z
