---
ID: "751f1df7-30db-4919-9126-00e5cc42066c"
Parent: "39ec8240-7ccb-4754-954d-7aca2458e35c"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Habitat Sites/Product Bundle/Product Bundle
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/new_package.png
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductBundle
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Sitecore.HabitatHome.Feature.ProductBundle.Controllers.ProductBundleController, Sitecore.HabitatHome.Feature.ProductBundle
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180430T135422Z
