---
ID: "a7fa7d01-1997-423a-bdd7-2eb8198cf8c0"
Parent: "14807d83-9671-4d70-b0f4-f54012f2bfb8"
Template: "14807d83-9671-4d70-b0f4-f54012f2bfb8"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Pages/Guide Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180214T035808Z
