---
ID: "cfd79d90-3d0f-4e85-a5ee-24de541eb95a"
Parent: "7eda2f15-9386-4476-b13a-ede1c54c3980"
Template: "e4c31926-ea66-4393-b9f7-a622e9ad5a30"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Settings/Commerce/Control Panel Configuration
DB: master
SharedFields:
- ID: "a710131d-0a6a-4565-8260-2d633c483e8a"
  Hint: Control Panel Configuration
  Value: "{2F395077-DA43-4935-B85C-29AE53A62F50}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190807T182849Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
