---
ID: "9bae60b5-acbe-4546-9e37-eb4b695354b7"
Parent: "7eda2f15-9386-4476-b13a-ede1c54c3980"
Template: "64048ab3-e570-4f49-a658-68c1e3c645dd"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Settings/Commerce/Product List Cache Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190807T182846Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
