---
ID: "5d43fca8-d83f-4c62-b85f-f6b078df4816"
Parent: "8c4c09fa-c2ae-4c0f-9b8b-3b341d36e8b8"
Template: "bf680756-b2fa-4cae-8b69-ee361080616f"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Presentation/Partial Designs/Commerce/Product Page Content
DB: master
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "default-main-product-page-content"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{63FE899A-2101-4021-9C41-825775DFD280}"
          p:before="*"
          s:id="{BFBD9DE2-3ABF-4078-BBCB-C95C5B2D863F}"
          s:par="Separator=%3e&amp;FieldNames=%7b137235E6-E38A-46B1-AC30-0E6151F06CA0%7d&amp;GridParameters=%7b113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7d&amp;Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0"
          s:ph="/main/container-5" />
        <r
          uid="{0E4CA240-23C7-4113-BA2D-608BF005638F}"
          p:after="r[@uid='{63FE899A-2101-4021-9C41-825775DFD280}']"
          s:ds=""
          s:id="{C25766C8-9AFD-4D28-87FE-147774F6806D}"
          s:par="SplitterSize=2&amp;EnabledPlaceholders=1%2C2&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles8&amp;ColumnWidth1=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D%7C%7BF6DC722E-15DB-4826-920B-ACCFDA772432%7D&amp;ColumnWidth2=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D%7C%7BF6DC722E-15DB-4826-920B-ACCFDA772432%7D&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;Reset Caching Options&amp;DynamicPlaceholderId=4"
          s:ph="/main/container-5" />
        <r
          uid="{99B05F8C-7B36-494F-A0F3-9ABC288736D9}"
          p:after="r[@uid='{0E4CA240-23C7-4113-BA2D-608BF005638F}']"
          s:ds=""
          s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;BackgroundImage&amp;Styles=%7B28C65397-7759-49B0-B39F-AFBC6F5D508A%7D&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=5"
          s:ph="main" />
        <r
          uid="{CD1F2857-06D5-475B-A22B-59A8CA828FD0}"
          p:after="r[@uid='{99B05F8C-7B36-494F-A0F3-9ABC288736D9}']"
          s:ds=""
          s:id="{24A792CF-1F2A-4A0D-9CEE-89B6BC696C55}"
          s:par=""
          s:ph="/main/container-5/column-1-4" />
        <r
          uid="{28420462-9874-4307-9A1F-E4DD2B2CC4E1}"
          p:after="r[@uid='{CD1F2857-06D5-475B-A22B-59A8CA828FD0}']"
          s:ds=""
          s:id="{958D6FFB-6715-46CA-9670-683D422D2B58}"
          s:par=""
          s:ph="/main/container-5/column-1-4" />
        <r
          uid="{5508BEE5-D82B-4853-BEEF-BEDF5E6F8370}"
          p:after="r[@uid='{28420462-9874-4307-9A1F-E4DD2B2CC4E1}']"
          s:ds=""
          s:id="{C1F44E19-5B84-4B2C-9386-8D189476028D}"
          s:par="GridParameters=%7b22138ACE-6737-4031-9552-60D587D38D9E%7d%7c%7b5D87E990-D33A-4613-BE6D-0D0235197254%7d%7c%7b1864351A-0EDC-4650-95C0-7AB675D646AF%7d%7c%7b2A09D451-70CD-4A11-868C-3C56B6A7749C%7d&amp;Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0"
          s:ph="/main/container-5/column-1-4" />
        <r
          uid="{86EC009D-C8D1-4F73-9F50-A3605856688A}"
          p:after="r[@uid='{5508BEE5-D82B-4853-BEEF-BEDF5E6F8370}']"
          s:ds="{9BE164EF-7142-4497-85CA-FB53F509516C}"
          s:id="{C4222625-2637-43FE-82D7-341009A277CA}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D"
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{C203820F-5ABF-46CE-BE74-FF6187BEA43F}"
          p:after="r[@uid='{86EC009D-C8D1-4F73-9F50-A3605856688A}']"
          s:ds="{8F4104BA-9CCD-47F0-8F53-6FCD694138DD}"
          s:id="{64B12137-C6CE-423D-B29C-9BD7EAD1D76E}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D"
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{62FB9058-126D-491B-B693-ED9A43DA577B}"
          p:after="r[@uid='{C203820F-5ABF-46CE-BE74-FF6187BEA43F}']"
          s:ds="{82F5250C-1122-43BD-A5BD-6959376CFFC3}"
          s:id="{B79DF484-3464-441A-811C-DC1BFEED8CA1}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{92C7EFA3-02C1-4B74-81D1-DC3CCC69EA94}"
          p:after="r[@uid='{62FB9058-126D-491B-B693-ED9A43DA577B}']"
          s:ds=""
          s:id="{32C08A8F-1576-4DED-905D-DDAB77466027}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{B1D0CD1A-21D9-41A6-8C5F-2C6C3C9CFE66}"
          p:after="r[@uid='{92C7EFA3-02C1-4B74-81D1-DC3CCC69EA94}']"
          s:ds="{E679D02C-76B3-4B37-ADF1-7F8E510FC44E}"
          s:id="{63B19D58-0764-495A-80CB-4B06C99C3F70}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{77031979-8B4E-4C72-987A-EAE011D37A38}"
          p:after="r[@uid='{B1D0CD1A-21D9-41A6-8C5F-2C6C3C9CFE66}']"
          s:ds="{17426A3E-78CA-4F99-813E-E8911E1EABEC}"
          s:id="{93BC3DB7-582A-48EE-ADE8-F410561FA411}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{4895AFA7-452D-4196-A44B-9BF88B6EA938}"
          p:after="r[@uid='{77031979-8B4E-4C72-987A-EAE011D37A38}']"
          s:ds=""
          s:id="{E47E2CD3-D700-43C9-BDDD-B262963A52A4}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{E6843734-3693-4B61-A397-A311603C818F}"
          p:after="r[@uid='{4895AFA7-452D-4196-A44B-9BF88B6EA938}']"
          s:ds=""
          s:id="{BEA41D94-7D94-4347-9491-18198338B56D}"
          s:par=""
          s:ph="/main/container-5/column-2-4" />
        <r
          uid="{B151B4B4-DF47-44E7-95B5-9A1F789FD20B}"
          p:after="*[1=2]"
          s:ds="{6238B3BB-E9C4-4AFB-B445-BE302466691E}"
          s:id="{162AB463-0CE1-4295-8F7E-2E2E969984ED}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BF7387559-D67B-4CE9-8AE9-F5982850E73F%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
          s:ph="/main">
          <rls>
            <ruleset>
              <rule
                uid="{D494826B-40DC-470B-8AC0-CF01A58A2ECB}"
                s:name="show on health pdps">
                <conditions>
                  <condition
                    uid="D1CDF47FC65344AE938F0291C7BC3237"
                    s:id="{9F104E38-5D05-415F-A37C-45AC73AF03AF}"
                    s:CategoryPath="/sitecore/Commerce/Catalog Management/Catalogs/Habitat_Master/Habitat_Master-Departments/Habitat_Master-Health  Beauty and Fitness" />
                </conditions>
              </rule>
              <rule
                uid="{00000000-0000-0000-0000-000000000000}"
                s:name="Default">
                <conditions>
                  <condition
                    uid="AEB3D6C6781B4BBA92D0C2BB6D105272"
                    s:id="{4888ABBB-F17D-4485-B14B-842413F88732}" />
                </conditions>
                <actions>
                  <action
                    uid="55977B04364E44308A752D2C0CC64CD1"
                    s:id="{25F351A1-712D-45F8-857D-8AD95BB2ACE9}" />
                </actions>
              </rule>
            </ruleset>
          </rls>
        </r>
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4A1F7980-D0D8-4A43-867C-F546672F6B17}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190306T184023Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
