---
ID: "86014c85-d4cc-4ef4-a4b7-b24bc1b22133"
Parent: "2b056b9d-9332-407e-82f8-9c4bf8438cb0"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/Habitat Sites/Habitat Home Store/styles/product-list-itemsonpage-component"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/86014C85D4CC4EF4A4B7B24BC1B22133.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "130b4a3b-19c5-425d-9256-0ba8068a934d"
  Value: LypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyogYnJlYWtwb2ludHMgKi8KLmN4YS1wcm9kdWN0bGlzdGl0ZW1zb25wYWdlLWNvbXBvbmVudCwKLmN4YS1wcm9kdWN0bGlzdGl0ZW1zcGVycGFnZS1jb21wb25lbnQgewogIGZvbnQtd2VpZ2h0OiBib2xkOwp9CgpAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDc2OHB4KSB7CiAgLmN4YS1wcm9kdWN0bGlzdGl0ZW1zb25wYWdlLWNvbXBvbmVudCAucHJvZHVjdGxpc3QtaGVhZGVyLXNlY3Rpb24sCiAgLmN4YS1wcm9kdWN0bGlzdGl0ZW1zcGVycGFnZS1jb21wb25lbnQgLnByb2R1Y3RsaXN0LWhlYWRlci1zZWN0aW9uIHsKICAgIC13ZWJraXQtYm94LXBhY2s6IGVuZCAhaW1wb3J0YW50OwogICAgLW1zLWZsZXgtcGFjazogZW5kICFpbXBvcnRhbnQ7CiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kICFpbXBvcnRhbnQ7CiAgfQp9CgouY3hhLXByb2R1Y3RsaXN0aXRlbXNvbnBhZ2UtY29tcG9uZW50IC5yZXN1bHRzLWNvbnRhaW5lciwKLmN4YS1wcm9kdWN0bGlzdGl0ZW1zcGVycGFnZS1jb21wb25lbnQgLnJlc3VsdHMtY29udGFpbmVyIHsKICBwb3NpdGlvbjogcmVsYXRpdmU7Cn0KCi5jeGEtcHJvZHVjdGxpc3RpdGVtc29ucGFnZS1jb21wb25lbnQgLnJlc3VsdHMtY29udGFpbmVyIHNwYW4sCi5jeGEtcHJvZHVjdGxpc3RpdGVtc3BlcnBhZ2UtY29tcG9uZW50IC5yZXN1bHRzLWNvbnRhaW5lciBzcGFuIHsKICBjb2xvcjogIzAwMCAhaW1wb3J0YW50Owp9CgouY3hhLXByb2R1Y3RsaXN0aXRlbXNvbnBhZ2UtY29tcG9uZW50IC5yZXN1bHRzLWNvbnRhaW5lcjphZnRlciwKLmN4YS1wcm9kdWN0bGlzdGl0ZW1zcGVycGFnZS1jb21wb25lbnQgLnJlc3VsdHMtY29udGFpbmVyOmFmdGVyIHsKICBjb250ZW50OiAiXGYwNzgiOwogIGZvbnQtZmFtaWx5OiBGb250QXdlc29tZTsKICBjb2xvcjogIzAwMDsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgcmlnaHQ6IDEwcHg7CiAgdG9wOiA1MCU7CiAgLXdlYmtpdC10cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7CiAgLW1zLXRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNTAlKTsKICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7CiAgei1pbmRleDogMTA7CiAgdGV4dC1hbGlnbjogY2VudGVyOwogIHBvaW50ZXItZXZlbnRzOiBub25lOwp9CgouY3hhLXByb2R1Y3RsaXN0aXRlbXNvbnBhZ2UtY29tcG9uZW50IC5jaGFuZ2UtcGFnZXNpemUsCi5jeGEtcHJvZHVjdGxpc3RpdGVtc3BlcnBhZ2UtY29tcG9uZW50IC5jaGFuZ2UtcGFnZXNpemUgewogIGZvbnQtd2VpZ2h0OiBub3JtYWw7CiAgd2lkdGg6IDEyZW07CiAgaGVpZ2h0OiAyLjU2MjVlbTsKICAtd2Via2l0LWFwcGVhcmFuY2U6IG5vbmU7CiAgLW1vei1hcHBlYXJhbmNlOiBub25lOwogIC1vLWFwcGVhcmFuY2U6IG5vbmU7CiAgYmFja2dyb3VuZC1hdHRhY2htZW50OiBzY3JvbGw7CiAgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7CiAgYmFja2dyb3VuZC1pbWFnZTogbm9uZTsKICBiYWNrZ3JvdW5kLXBvc2l0aW9uOiAwJSAwJTsKICBiYWNrZ3JvdW5kLXJlcGVhdDogcmVwZWF0OwogIGNvbG9yOiAjMDAwOwogIGJhY2tncm91bmQtY29sb3I6ICNmZmY7CiAgZm9udC1zaXplOiAxNnB4OwogIGZvbnQtd2VpZ2h0OiA0MDA7CiAgbGluZS1oZWlnaHQ6IG5vcm1hbDsKICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgcGFkZGluZzogMDsKICBtYXJnaW46IDA7CiAgd2lkdGg6IGF1dG87CiAgaGVpZ2h0OiA0MXB4OwogIG1heC13aWR0aDogMTAwJTsKICBib3JkZXI6IDFweCBzb2xpZCAjZDhkOWQ1OwogIGJvcmRlci1yYWRpdXM6IDA7CiAgb3V0bGluZTogbm9uZTsKICBwYWRkaW5nLWxlZnQ6IDEwcHg7CiAgcGFkZGluZy1yaWdodDogMzVweDsKICBwYWRkaW5nOiAwIDJlbSAwIDAuOTM3NWVtOwogIHBvc2l0aW9uOiByZWxhdGl2ZTsKfQo=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 3320
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: text/css
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: css
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032455Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032455Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032455Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
