---
ID: "981b6dc0-28db-4704-868f-08953e257c68"
Parent: "2b056b9d-9332-407e-82f8-9c4bf8438cb0"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/Habitat Sites/Habitat Home Store/styles/product-list-sorting-component"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/981B6DC028DB4704868F08953E257C68.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "28ca256e-0331-47a1-94d3-e87765960b19"
  Value: LypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyogYnJlYWtwb2ludHMgKi8KLmN4YS1wcm9kdWN0bGlzdHNvcnRpbmctY29tcG9uZW50IHsKICBmb250LXdlaWdodDogYm9sZDsKfQoKQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA3NjhweCkgewogIC5jeGEtcHJvZHVjdGxpc3Rzb3J0aW5nLWNvbXBvbmVudCAucHJvZHVjdGxpc3QtaGVhZGVyLXNlY3Rpb24gewogICAgdGV4dC1hbGlnbjogcmlnaHQ7CiAgfQp9CgouY3hhLXByb2R1Y3RsaXN0c29ydGluZy1jb21wb25lbnQgLlNvcnQtQnktY29udGFpbmVyIHsKICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgcG9zaXRpb246IHJlbGF0aXZlOwp9CgouY3hhLXByb2R1Y3RsaXN0c29ydGluZy1jb21wb25lbnQgLlNvcnQtQnktY29udGFpbmVyOmFmdGVyIHsKICBjb250ZW50OiAiXGYwNzgiOwogIGZvbnQtZmFtaWx5OiBGb250QXdlc29tZTsKICBjb2xvcjogIzAwMDsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgcmlnaHQ6IDEwcHg7CiAgdG9wOiA1MCU7CiAgLXdlYmtpdC10cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7CiAgLW1zLXRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNTAlKTsKICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7CiAgei1pbmRleDogMTA7CiAgdGV4dC1hbGlnbjogY2VudGVyOwogIHBvaW50ZXItZXZlbnRzOiBub25lOwp9CgouY3hhLXByb2R1Y3RsaXN0c29ydGluZy1jb21wb25lbnQgLnNvcnQtZHJvcGRvd24gewogIGZvbnQtd2VpZ2h0OiBub3JtYWw7CiAgd2lkdGg6IDEyZW07CiAgaGVpZ2h0OiAyLjU2MjVlbTsKICAtd2Via2l0LWFwcGVhcmFuY2U6IG5vbmU7CiAgLW1vei1hcHBlYXJhbmNlOiBub25lOwogIC1vLWFwcGVhcmFuY2U6IG5vbmU7CiAgYmFja2dyb3VuZC1hdHRhY2htZW50OiBzY3JvbGw7CiAgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7CiAgYmFja2dyb3VuZC1pbWFnZTogbm9uZTsKICBiYWNrZ3JvdW5kLXBvc2l0aW9uOiAwJSAwJTsKICBiYWNrZ3JvdW5kLXJlcGVhdDogcmVwZWF0OwogIGNvbG9yOiAjMDAwOwogIGJhY2tncm91bmQtY29sb3I6ICNmZmY7CiAgZm9udC1zaXplOiAxNnB4OwogIGZvbnQtd2VpZ2h0OiA0MDA7CiAgbGluZS1oZWlnaHQ6IG5vcm1hbDsKICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgcGFkZGluZzogMDsKICBtYXJnaW46IDA7CiAgd2lkdGg6IGF1dG87CiAgaGVpZ2h0OiA0MXB4OwogIG1heC13aWR0aDogMTAwJTsKICBib3JkZXI6IDFweCBzb2xpZCAjZDhkOWQ1OwogIGJvcmRlci1yYWRpdXM6IDA7CiAgb3V0bGluZTogbm9uZTsKICBwYWRkaW5nLWxlZnQ6IDEwcHg7CiAgcGFkZGluZy1yaWdodDogMzVweDsKICBwYWRkaW5nOiAwIDJlbSAwIDAuOTM3NWVtOwogIHBvc2l0aW9uOiByZWxhdGl2ZTsKfQoKLyoNCi5jeGEtcHJvZHVjdGxpc3Rzb3J0aW5nLWNvbXBvbmVudCB7DQogICBwYWRkaW5nOjBweDsNCiAgIC5wcm9kdWN0bGlzdC1oZWFkZXItc2VjdGlvbiB7DQogICAgICAgLy9AaW5jbHVkZSByb3ctb2YtZWxlbWVudHMtd2lkZS1hcGFydChmYWxzZSwgJGNlbnRlcik7DQogICAgICAgLlNvcnQtQnktY29udGFpbmVyIHsNCiAgICAgICAgICAgLy9AaW5jbHVkZSByb3ctb2YtZWxlbWVudHMtcGFja2VkKGZhbHNlLCAkY2VudGVyLCAkcGFja2VkLWVsZW1lbnRzLW1hcmdpbik7DQogICAgICAgICAgIGxpbmUtaGVpZ2h0OiAyMnB4Ow0KICAgICAgICAgICBzZWxlY3Qgew0KICAgICAgICAgICAgICAgd2lkdGg6IDI0MHB4Ow0KICAgICAgICAgICB9DQogICAgICAgICAgIHNwYW4gew0KICAgICAgICAgICAgICAgY29sb3I6ICRzZWNvbmRhcnktdGV4dC1jb2xvcjsNCiAgICAgICAgICAgfQ0KICAgICAgIH0NCiAgIH0NCiAgIG1hcmdpbi1ib3R0b206ICRtYXJnaW4qMjsNCn0NCiovCg==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 3283
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: text/css
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: css
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032513Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032513Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032513Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T032513Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
