---
ID: "c533dba5-2808-4e06-9be9-e851fcddf002"
Parent: "2b056b9d-9332-407e-82f8-9c4bf8438cb0"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/Habitat Sites/Habitat Home Store/styles/product-facet-component"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/C533DBA528084E069BE9E851FCDDF002.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "582b55d8-9121-4286-9007-48a10d54f8f6"
  Value: QGNoYXJzZXQgIlVURi04IjsKLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLmN4YS1wcm9kdWN0ZmFjZXRzLWNvbXBvbmVudCB7CiAgcGFkZGluZzogMjBweDsKICBtYXJnaW4tYm90dG9tOiAxNXB4OwogIGJveC1zaGFkb3c6IDAgMXB4IDRweCAwIHJnYmEoMCwgMCwgMCwgMC4xKTsKICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmOwogIGJvcmRlci1yYWRpdXM6IDRweDsKICBwYWRkaW5nLWJvdHRvbTogOHB4Owp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCB7CiAgcGFkZGluZy10b3A6IDVweDsKICBsaW5lLWhlaWdodDogMTsKICBtYXJnaW4tYm90dG9tOiA0MHB4Owp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCAuZmFjZXQtdGl0bGUgewogIGN1cnNvcjogcG9pbnRlcjsKICAtd2Via2l0LXVzZXItc2VsZWN0OiBub25lOwogIC1tb3otdXNlci1zZWxlY3Q6IG5vbmU7CiAgLW1zLXVzZXItc2VsZWN0OiBub25lOwogIHVzZXItc2VsZWN0OiBub25lOwogIGNvbG9yOiAjNmI3MTdiICFpbXBvcnRhbnQ7CiAgdGV4dC10cmFuc2Zvcm06IGxvd2VyY2FzZTsKICBtYXJnaW4tYm90dG9tOiA1cHg7CiAgZm9udC1zaXplOiAxNnB4Owp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCAuZmFjZXQtdGl0bGU6YWZ0ZXIgewogIGZsb2F0OiByaWdodDsKfQoKLmN4YS1wcm9kdWN0ZmFjZXRzLWNvbXBvbmVudCAuY29tcG9uZW50LWNvbnRlbnQgLmZhY2V0LXRpdGxlOmFmdGVyIHsKICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgZm9udC1mYW1pbHk6ICJTQ0NYQUlDT05TIjsKICBmb250LXN0eWxlOiBub3JtYWw7CiAgLXdlYmtpdC1mb250LXNtb290aGluZzogYW50aWFsaWFzZWQ7CiAgY29udGVudDogIu6nhSI7CiAgZm9udC1zaXplOiA4cHg7CiAgY29sb3I6ICM3NDdhODM7CiAgZm9udC13ZWlnaHQ6IG5vcm1hbDsKICBtYXJnaW4tdG9wOiA1cHg7Cn0KCi5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IC5mYWNldC10aXRsZTpmaXJzdC1sZXR0ZXIgewogIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7Cn0KCi5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIHsKICBtYXJnaW46IDA7Cn0KCi5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIGxpIHsKICBwYWRkaW5nOiAycHggMHB4Owp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaS5hY3RpdmUgewogIGZvbnQtd2VpZ2h0OiBib2xkOwp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaTpsYXN0LWNoaWxkIHsKICBtYXJnaW4tYm90dG9tOiA0cHg7Cn0KCi5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIGxpIGEgewogIGxpbmUtaGVpZ2h0OiAyM3B4Owp9CgouY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaSBhIHNwYW4sIC5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIGxpIGEgewogIGZvbnQtc2l6ZTogMTNweDsKICBjb2xvcjogIzc0N2E4MzsKfQoKLmN4YS1wcm9kdWN0ZmFjZXRzLWNvbXBvbmVudCAuY29tcG9uZW50LWNvbnRlbnQgdWwgbGkgYSBzcGFuOmhvdmVyLCAuY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaSBhIHNwYW46YWN0aXZlLCAuY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaSBhIHNwYW46Zm9jdXMsIC5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIGxpIGE6aG92ZXIsIC5jeGEtcHJvZHVjdGZhY2V0cy1jb21wb25lbnQgLmNvbXBvbmVudC1jb250ZW50IHVsIGxpIGE6YWN0aXZlLCAuY3hhLXByb2R1Y3RmYWNldHMtY29tcG9uZW50IC5jb21wb25lbnQtY29udGVudCB1bCBsaSBhOmZvY3VzIHsKICBiYWNrZ3JvdW5kOiBub25lOwogIGNvbG9yOiAjMGU5MDlmOwogIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKfQo=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 3533
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: text/css
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: css
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T033848Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T033849Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T033850Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180608T033849Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
