---
ID: "48c5fb79-7f10-41f6-9776-1c9b03ce1493"
Parent: "3ef3a3ec-1015-472e-9fd4-6246f11c0338"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/Habitat Sites/Habitat Home Store/sass/components/commerce/product-bundle"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/54A5E0A4584748689843F47A566C1CDA.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "948ee382-a289-4c8e-8ed2-27b57c0b1edd"
  Value: QGltcG9ydCAiLi4vLi4vaW5kZXgiOw0KDQouY3hhLXByb2R1Y3RidW5kbGUtY29tcG9uZW50IHsNCiAgICBwYWRkaW5nOiAkc3RhbmRhcmRTcGFjaW5nOw0KICAgIGJhY2tncm91bmQ6ICRsaWdodDsNCiAgICBib3JkZXItcmFkaXVzOiAkYm9yZGVyLXJhZGl1czsNCiAgICBib3gtc2hhZG93OiAwIDFweCA0cHggMCByZ2JhKDAsIDAsIDAsIDAuMSk7DQogICAgLmJ1bmRsZS10aXRsZSB7DQogICAgICAgIHBhZGRpbmc6ICRwYWRkaW5nIDA7DQogICAgICAgIGZvbnQtZmFtaWx5OiAiS2lldml0UHJvIiAhaW1wb3J0YW50Ow0KICAgICAgICBsaW5lLWhlaWdodDogMTUwJTsNCiAgICAgICAgZm9udC13ZWlnaHQ6IGJvbGQgIWltcG9ydGFudDsNCiAgICB9DQogICAgLmJ1bmRsZS1ncm91cCB7DQogICAgICAgIHBhZGRpbmc6ICRwYWRkaW5nLzIgMCAkcGFkZGluZy8yIDA7DQogICAgICAgIGN1cnNvcjogcG9pbnRlcjsNCiAgICAgICAgLmJ1bmRsZS1ncm91cC1oZWFkZXItY29udGFpbmVyIHsNCiAgICAgICAgICAgIHBhZGRpbmc6ICRwYWRkaW5nIDAgJHBhZGRpbmcgMDsNCiAgICAgICAgICAgIC5idW5kbGUtZ3JvdXAtaGVhZGVyIHsNCiAgICAgICAgICAgICAgICBkaXNwbGF5OiBmbGV4Ow0KICAgICAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjsNCiAgICAgICAgICAgICAgICBhbGlnbi1pdGVtczogYmFzZWxpbmU7DQogICAgICAgICAgICAgICAgLmJ1bmRsZS1ncm91cC1wcm9kdWN0LW5hbWUgew0KICAgICAgICAgICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7DQogICAgICAgICAgICAgICAgICAgIHdpZHRoOiAxMDAlOw0KICAgICAgICAgICAgICAgICAgICBwYWRkaW5nLXJpZ2h0OiAkbWFyZ2luICsgMzBweDsgLy8gLmNvbGxhcHNlLWFycm93IHJpZ2h0ICsgLmNvbGxhcHNlLWFycm93IGljb24gc2l6ZQ0KICAgICAgICAgICAgICAgICAgICBzcGFuIHsNCiAgICAgICAgICAgICAgICAgICAgICAgIGxpbmUtaGVpZ2h0OiAzMHB4Ow0KICAgICAgICAgICAgICAgICAgICAgICAgZm9udC1zaXplOiAxNnB4Ow0KICAgICAgICAgICAgICAgICAgICAgICAgZm9udC1mYW1pbHk6ICJLaWV2aXRQcm8iICFpbXBvcnRhbnQ7DQogICAgICAgICAgICAgICAgICAgICAgICBmb250LXdlaWdodDogMzAwOw0KICAgICAgICAgICAgICAgICAgICAgICAgY29sb3I6ICRoZWFkaW5nLWNvbG9yOw0KICAgICAgICAgICAgICAgICAgICAgICAgb3BhY2l0eTogMC44Ow0KICAgICAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIC5jb2xsYXBzZS1hcnJvdyB7DQogICAgICAgICAgICAgICAgICAgIG1hcmdpbi1yaWdodDogJG1hcmdpbjsNCiAgICAgICAgICAgICAgICAgICAgbGluZS1oZWlnaHQ6IDMwcHg7DQogICAgICAgICAgICAgICAgICAgIEBpbmNsdWRlIHNjLWljb24oKTsNCiAgICAgICAgICAgICAgICAgICAgJjphZnRlciB7DQogICAgICAgICAgICAgICAgICAgICAgICBAaW5jbHVkZSBzYy1pY29uKCRzY3hhLWNoZXZyb25kb3duKTsNCiAgICAgICAgICAgICAgICAgICAgICAgIGZvbnQtc2l6ZTogMTBweDsNCiAgICAgICAgICAgICAgICAgICAgICAgIGNvbG9yOiByZ2JhKDAsIDAsIDAsIDAuNCk7DQogICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgLnByb2R1Y3QtbGluayB7DQogICAgICAgICAgICAgICAgICAgIGRpc3BsYXk6IG5vbmU7DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgLnNlbGVjdGVkLXZhcmlhbnQtcHJldmlldyB7DQogICAgICAgICAgICAgICAgZGlzcGxheTogZmxleDsNCiAgICAgICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtc3RhcnQ7DQogICAgICAgICAgICAgICAgZmxleC13cmFwOiB3cmFwOw0KICAgICAgICAgICAgICAgIC5zZWxlY3RlZC12YXJpYW50LWdyb3VwIHsNCiAgICAgICAgICAgICAgICAgICAgcGFkZGluZzogJHBhZGRpbmcgMCAkcGFkZGluZyAwOw0KICAgICAgICAgICAgICAgICAgICArIC5zZWxlY3RlZC12YXJpYW50LWdyb3VwIHsNCiAgICAgICAgICAgICAgICAgICAgICAgIG1hcmdpbi1sZWZ0OiAkbWFyZ2luOw0KICAgICAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgICAgIC5zZWxlY3RlZC12YWx1ZSB7DQogICAgICAgICAgICAgICAgICAgICAgICBmb250LXdlaWdodDogYm9sZDsNCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICAuYnVuZGxlLWdyb3VwLWJvZHktY29udGFpbmVyIHsNCiAgICAgICAgICAgIGRpc3BsYXk6IG5vbmU7DQogICAgICAgICAgICAuZ3JvdXAtdmFyaWFudC1zZWN0aW9uIHsNCiAgICAgICAgICAgICAgICBkaXNwbGF5OiBmbGV4Ow0KICAgICAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47DQogICAgICAgICAgICAgICAgLmdyb3VwLXZhcmlhbnQtc2VsZWN0aW9uIHsNCiAgICAgICAgICAgICAgICAgICAgKyAuZ3JvdXAtdmFyaWFudC1zZWxlY3Rpb24gew0KICAgICAgICAgICAgICAgICAgICAgICAgbWFyZ2luLXRvcDogJHN0YW5kYXJkU3BhY2luZzsNCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgICAgICAuZ3JvdXAtdmFyaWFudC1sYWJlbCB7DQogICAgICAgICAgICAgICAgICAgICAgICB3aWR0aDogMTAwJTsNCiAgICAgICAgICAgICAgICAgICAgICAgIGxpbmUtaGVpZ2h0OiAyNXB4Ow0KICAgICAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgICAgIC5ncm91cC12YXJpYW50LXNlbGVjdCB7DQogICAgICAgICAgICAgICAgICAgICAgICB3aWR0aDogMTAwJTsNCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIC5wcm9kdWN0LWxpbmsgew0KICAgICAgICAgICAgICAgIG1hcmdpbjogJG1hcmdpbiAwOw0KICAgICAgICAgICAgfQ0KICAgICAgICB9DQogICAgICAgICYuYWN0aXZlIHsNCiAgICAgICAgICAgIC5idW5kbGUtZ3JvdXAtaGVhZGVyLWNvbnRhaW5lciB7DQogICAgICAgICAgICAgICAgLmJ1bmRsZS1ncm91cC1oZWFkZXIgew0KICAgICAgICAgICAgICAgICAgICAucHJvZHVjdC1uYW1lIHsNCiAgICAgICAgICAgICAgICAgICAgICAgIGg0IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb2xvcjogJHByaW1hcnktY29sb3IgIWltcG9ydGFudDsNCiAgICAgICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgICAgICAuY29sbGFwc2UtYXJyb3cgew0KICAgICAgICAgICAgICAgICAgICAgICAgJjphZnRlciB7DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgY29sb3I6ICRwcmltYXJ5LWNvbG9yOw0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBpbmNsdWRlIHNjLWljb24oJHNjeGEtY2hldnJvbnVwKTsNCiAgICAgICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAuc2VsZWN0ZWQtdmFyaWFudC1wcmV2aWV3IHsNCiAgICAgICAgICAgICAgICAgICAgZGlzcGxheTogbm9uZTsNCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgICAgJi5ub1ZhcmlhbnRzIHsNCiAgICAgICAgICAgIC5idW5kbGUtZ3JvdXAtaGVhZGVyLWNvbnRhaW5lciB7DQogICAgICAgICAgICAgICAgLmJ1bmRsZS1ncm91cC1oZWFkZXIgew0KICAgICAgICAgICAgICAgICAgICAuYnVuZGxlLWdyb3VwLXByb2R1Y3QtbmFtZSB7DQogICAgICAgICAgICAgICAgICAgICAgICB3aWR0aDogY2FsYygxMDAlIC0gMTEwcHgpOyAvLyBtaW51cyBwcm9kdWN0IGxpbmsgd2lkdGgNCiAgICAgICAgICAgICAgICAgICAgICAgIHBhZGRpbmctcmlnaHQ6IDA7DQogICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAgICAgLmNvbGxhcHNlLWFycm93IHsNCiAgICAgICAgICAgICAgICAgICAgICAgIGRpc3BsYXk6IG5vbmU7DQogICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAgICAgLnByb2R1Y3QtbGluayB7DQogICAgICAgICAgICAgICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7DQogICAgICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgICAgLnByb2R1Y3QtbGluayB7DQogICAgICAgICAgICB0ZXh0LWFsaWduOiByaWdodDsNCiAgICAgICAgICAgIGEgew0KICAgICAgICAgICAgICAgIGZvbnQtd2VpZ2h0OiA1MDA7DQogICAgICAgICAgICAgICAgY29sb3I6ICRwcmltYXJ5LWNvbG9yOw0KICAgICAgICAgICAgICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsNCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgIH0NCiAgICAuYnVuZGxlLWdyb3Vwcy1jb250YWluZXIgPiAqOm5vdCg6bGFzdC1jaGlsZCksDQogICAgLmJ1bmRsZS1oZWFkZXIgew0KICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2U0ZTdlYzsNCiAgICB9DQp9DQo=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 4607
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: scss
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T065110Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T065108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T065107Z
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T065108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T065109Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
