---
ID: "8ade3955-6367-42a9-bbd0-b36568229c97"
Parent: "ead66b75-97b8-4bb7-8e22-94fedbda140d"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Habitat Home Store/scripts/components/ProductRelatedContent
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 288
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190305T182638Z
