---
ID: "d4b28076-40af-4202-9a32-09047c9a0046"
Parent: "ee3bc3a7-7e4e-43d8-98f8-38906ffd08a2"
Template: "7c02e9f5-54b5-4ef4-bd10-f4c5d448a48c"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Presentation/Rendering Variants/Product Bundle/Default/Bundle Groups Container/Bundle Groups Reference/Bundle Group/Bundle Group Body Container/Product Link Container/Product Link
DB: master
SharedFields:
- ID: "1aa68c0b-eb67-4575-9ca8-1689c2aff091"
  Hint: Tag
  Value: "{FF819CDE-E98A-4AB7-B8B0-65EE989369F7}"
- ID: "34400b24-5666-4295-bbc2-b87c2020aa6d"
  Hint: LinkAttributes
  Value: 
- ID: "8414031e-7b85-426c-8516-84d6223a1208"
  Hint: CssClass
  Value: "product-link"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 250
- ID: "c35b2285-b4a8-406f-a91c-24a60391dc12"
  Hint: DataAttributes
  Value: href=%40%28ProductLink%29
- ID: "f9926e84-399e-4070-b2ed-a31f6f542bdd"
  Hint: IsLink
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: Go to product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181205T073059Z
