---
ID: "a04ab82a-cf99-41f2-a3cf-8cf1937061fc"
Parent: "d162564a-aa46-44fd-b34c-8c004c6c5d2e"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Store/Product Related Content
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180605T172630Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
