---
ID: "fa885ebd-8968-493f-8e2d-d1f4ce516698"
Parent: "9241219a-8f66-4662-aefe-7bb19fb29b6d"
Template: "9241219a-8f66-4662-aefe-7bb19fb29b6d"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Store/Catalog/Commerce Category/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/barrels.png
- ID: "97fb669d-5b8e-4829-9a24-06418c315d73"
  Hint: SxaTags
  Value: "{8D31696A-6D7C-437D-ADAE-DA83E9FBC02D}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{F1FB8A76-9C0E-FCBB-3F7F-A57C84E92E39}"
- ID: "d4952280-2d7d-4bf4-a99a-ea36dad0f0a7"
  Hint: Body Css Class
  Value: "category-page"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190308T153353Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
