---
ID: "4365279a-3b9a-47db-9874-ec6c8d165cd1"
Parent: "8df41bda-9593-47ab-8d83-162990af8407"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Presentation/Rendering Variants/Product Bundle/Default
DB: master
SharedFields:
- ID: "6e87db8e-58a6-4613-823b-e99e244f07a0"
  Hint: ItemCssClassField
  Value: 
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "col-xs-12"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181127T020508Z
